### ISSUE TITLE
虚拟返回键会因为底部是白色背景而看不见？

### ISSUE THREAD

**Issue by ziyouxiaozi** [kongzue/BaseFramework#4]
当有虚拟返回键时会因为底部是白色背景而看不见？

**Comment by kongzue** [comment]
不理解您的意思

**Comment by ziyouxiaozi** [comment]
![image](https://user-images.githubusercontent.com/2511739/92704307-735e9600-f385-11ea-8c23-d9dda9fb964d.png)

**Comment by ziyouxiaozi** [comment]
![1599727748(1)](https://user-images.githubusercontent.com/2511739/92705273-2a5b1180-f386-11ea-9f84-48a177f44b8e.jpg)

**Comment by kongzue** [comment]
您好，这是Google的锅，我又尝试过给Dialog的Window增加暗色导航栏按钮Flag，但是是无效的

**Comment by kongzue** [comment]
请阅读《沉浸式》相关章节：https://github.com/kongzue/BaseFramework#%E6%B2%89%E6%B5%B8%E5%BC%8F
@DarkNavigationBarTheme(true)       //开启底部导航栏按钮暗色模式
使用此注解标记您的BaseActivity即可。
具体您可以参照Demo项目的实际代码。
